Repository wecode-bootcamp-korea/20-2nd-create101-frontend, pull requests merged in 2021-06, with the labels that each got.

#10 [20기 하연주] Refactor: 멘토님 리뷰 반영
  public/data/mainCarouselData.json
  public/images/mainCarouselImg/chart.jpg
  public/images/mainCarouselImg/flower.jpg
  public/images/mainCarouselImg/japan.jpg
  public/images/mainCarouselImg/polynesia.jpg
  public/images/mainCarouselImg/running.jpg
  public/images/mainCarouselImg/salad.jpg
  public/index.html
  src/Pages/Main/Components/MainCarousel/MainCarousel.js
  src/Pages/Main/Main.js
Labels: Status: 수정 요청

#11 [20기 조원영] 카테고리 페이지 클라스별 필터기능 구현 및 메인 페이지 클라스 리스트 맵 (멘토님 수정사항 반영)
  public/data/categoryData.json
  public/index.html
  src/Components/ClassCard/ClassCard.js
  src/Components/ClassCard/ClassCardList.js
  src/Pages/Category/Category.js
  src/Pages/Category/Components/CategoryCards.js
  src/Pages/Category/Components/PageButtons.js
  src/Pages/Category/Components/a.js
  src/Pages/Details/Details.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#12 [20기 조원영] Footer 구현 완료
  src/Components/Footer/Footer.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [20기 김도은] Add: My Page
  public/data/user.json
  src/Components/ClassCard/ClassCard.js
  src/Pages/CreateClass/CreateClass.js
  src/Pages/Login/Login.js
  src/Pages/MyPage/MyPage.js
  src/Routes.js
  src/Styles/cursor.cur
Labels: Status: Accepted

#5 [20기 하연주]Refactor: 멘토님 리뷰 반영
  public/data/categoryData.json
  src/Components/MobileNav/MobileNav.js
  src/Components/Nav/Components/ClickedSearchBar/ClickedSearchBar.js
  src/Components/Nav/Nav.js
  src/Pages/Category/Category.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
